AWSTemplateFormatVersion: 2010-09-09
Description: Regional Config Service Resources

Conditions:

  IsUsEast1: !Equals ["us-east-1", !Ref "AWS::Region"]

Resources:

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/config-recorder-role"
      RecordingGroup:
        AllSupported: True
        IncludeGlobalResourceTypes: !If [IsUsEast1, 'True', 'False']

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: TwentyFour_Hours
      S3BucketName: !Sub "config-bucket-${AWS::AccountId}"
      S3KeyPrefix: !Sub "AWSLogs/${AWS::AccountId}"
